### ISSUE TITLE
Can't connect account

### ISSUE THREAD

**Issue by sdaltons1** [theOrakle/everlightsv3#2]
Glad to hear you made some progress. I added the custom repository, downloaded it, restarted. 

I see "everlights bridge" in my list of integrations available to be added. When I click on it to begin the configuration, it prompts me to sign into my mill.com account. 

I did try entering my everlights email just to see if it was just a bad label but I get "unknown error occurred."

**Comment by theOrakle** [comment]
It connects locally - redownload 0.1.5 (I fixed the config_flow translations that I "borrowed" from my mill integration)

It should prompt for a host.  you can enter an IP or hostname if you have local DNS.

You have a mill food recycler too?

**Comment by sdaltons1** [comment]
I do not have any products or an account through mill.

The onboarding still prompts for the mill account but I typed the IP of my hub and it pushed through. 

So now the integration is seeing my hub but isn't producing any devices or entities. 

I'm not at home at the moment, though I don't see why that would matter. I will check again when I get home just to be sure.

**Comment by theOrakle** [comment]
I'm still figuring out the deployments/config_flows, but I'm pretty sure it is cached.

You will want to delete your hub and re-add it though.  it most likely stored your IP as your username in the config

**Comment by theOrakle** [comment]
<img width="1473" alt="image" src="https://github.com/theOrakle/everlightsv3/assets/37029980/a9c4dfe8-413a-4caf-86b2-386f41efc028">

**Comment by sdaltons1** [comment]
Still having the same problem.  I fiddled with the code for a little while but couldn't make any progress so I deleted what I had and redownloaded to make sure we are still working from the same page.  I have also deleted and re-added my bridge several times but it hasn't helped.

Here is the error I'm getting:

Error while setting up everlightsv3 platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/everlightsv3/light.py", line 20, in async_setup_entry
    host = config.data[CONF_HOST]
           ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'host'

**Comment by sdaltons1** [comment]
Hey, I've still been trying but can't get anywhere. Every time I remove and re-add my bridge, it's the same thing. Do you have any other ideas?

**Comment by theOrakle** [comment]
Delete the integration, the EverLights HACS integration, and restart. Then reinstall EverLights HACS integration and add the integration.

**Comment by sdaltons1** [comment]
![IMG_0073](https://github.com/theOrakle/everlightsv3/assets/93367436/f11a1f63-bb01-45aa-a8ce-3116c253ef53)
![IMG_0074](https://github.com/theOrakle/everlightsv3/assets/93367436/0fb2bbaa-04ce-4815-b0f2-1dc0d9e2690b)

Logger: homeassistant.components.light
Source: helpers/entity_platform.py:359
Integration: Light (documentation, issues)
First occurred: 9:37:19 AM (3 occurrences)
Last logged: 9:38:11 AM

Error while setting up everlightsv3 platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/everlightsv3/light.py", line 20, in async_setup_entry
    host = config.data[CONF_HOST]
           ~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'host'

That's what I get no matter what combination of deleting, restarting, re-adding. Every single time.

**Comment by theOrakle** [comment]
Yup - I can reproduce...

I'm getting my arms around this config flow of the setup.  Hang in there.

**Comment by sdaltons1** [comment]
All good! Let me know when you are ready for me to give it another shot.

**Comment by theOrakle** [comment]
Alright...  Delete the integration, the EverLights HACS integration, and restart. Then reinstall EverLights HACS integration (.0.2.0) and add the integration.  There is still some refresh issues, but you should have control of your light.

**Comment by borski** [comment]
@theOrakle do you have a list of “things still to do”? I’d be happy to help.

**Comment by sdaltons1** [comment]
Updated and seems to be working. Thank you and nice job!

Feel free to close this.

**Comment by theOrakle** [comment]
> @theOrakle do you have a list of “things still to do”? I’d be happy to help.

I do not yet...  I wanted to get it reverse engineered and rough functionality before Halloween.
